### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by bbigras** [cid-chan/peerix#6]
Do I need to set `publicKey`?

config
```nix
{
  services.peerix = {
    enable = true;
    openFirewall = true;
    privateKeyFile = "/home/bbigras/peerix/secret-key-file";
    publicKeyFile = "/home/bbigras/peerix/public-key-file";
  };
}
```

log
```
nov 15 13:27:28 desktop systemd[1]: Started Local p2p nix caching daemon.
nov 15 13:27:29 desktop peerix-start[221090]: INFO:peerix.local:Launching nix-serve.
nov 15 13:27:29 desktop peerix-start[221106]: 2021/11/15-13:27:29 Starman::Server (type Net::Server::PreFork) starting! pid(221106)
nov 15 13:27:29 desktop peerix-start[221106]: Binding to UNIX socket file "/tmp/tmpywsgb7_i/server.sock"
nov 15 13:27:29 desktop peerix-start[221106]: Setting gid to "65534 65534 65534"
nov 15 13:27:30 desktop peerix-start[221090]: [2021-11-15 13:27:30 -0500] [221090] [INFO] Running on http://0.0.0.0:12304 (CTRL + C to quit)
nov 15 13:27:30 desktop peerix-start[221090]: INFO:hypercorn.error:Running on http://0.0.0.0:12304 (CTRL + C to quit)

nov 15 13:28:46 desktop peerix-start[221090]: INFO:peerix.remote:Got request from 192.168.2.40:12304 for ym14zflh2wrw3iz88xag4kyasckgf9d6
nov 15 13:28:46 desktop peerix-start[221107]: cannot open connection to remote store 'daemon': reading from file: Connection reset by peer at /nix/store/gwsv39yc6sy4rl5xfiikmk3gw3ln4if5-nix-serve-0.2-e4675e3/libexec/nix-serve/nix-serve.psgi line 26.
nov 15 13:28:46 desktop peerix-start[221090]: ERROR:asyncio:Task exception was never retrieved
nov 15 13:28:46 desktop peerix-start[221090]: future: <Task finished name='Task-6' coro=<DiscoveryProtocol.respond() done, defined at /nix/store/njdzyd7mji3lk9kmwgp5yvwh0ccgaxp0-python3.9-peerix-0.0.1/lib/python3.9/site-packages/peerix/remote.py:87> exception=ValueError('not enough values to unpack (expected 2, got 1)')>
nov 15 13:28:46 desktop peerix-start[221090]: Traceback (most recent call last):
nov 15 13:28:46 desktop peerix-start[221090]:   File "/nix/store/njdzyd7mji3lk9kmwgp5yvwh0ccgaxp0-python3.9-peerix-0.0.1/lib/python3.9/site-packages/peerix/remote.py", line 90, in respond
nov 15 13:28:46 desktop peerix-start[221090]:     narinfo = await self.store.narinfo(hsh)
nov 15 13:28:46 desktop peerix-start[221090]:   File "/nix/store/njdzyd7mji3lk9kmwgp5yvwh0ccgaxp0-python3.9-peerix-0.0.1/lib/python3.9/site-packages/peerix/prefix.py", line 14, in narinfo
nov 15 13:28:46 desktop peerix-start[221090]:     info = await self.backend.narinfo(hsh)
nov 15 13:28:46 desktop peerix-start[221090]:   File "/nix/store/njdzyd7mji3lk9kmwgp5yvwh0ccgaxp0-python3.9-peerix-0.0.1/lib/python3.9/site-packages/peerix/local.py", line 67, in narinfo
nov 15 13:28:46 desktop peerix-start[221090]:     info = NarInfo.parse(await resp.text())
nov 15 13:28:46 desktop peerix-start[221090]:   File "/nix/store/njdzyd7mji3lk9kmwgp5yvwh0ccgaxp0-python3.9-peerix-0.0.1/lib/python3.9/site-packages/peerix/store.py", line 43, in parse
nov 15 13:28:46 desktop peerix-start[221090]:     k, v = line.split(":", 1)
nov 15 13:28:46 desktop peerix-start[221090]: ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by MaeIsBad** [comment]
The same error occured to me when the peerix user didn't have access to the nix daemon(it wasn't in nix.settings.allowed-users/nix.allowedUsers)

**Comment by danth** [comment]
Also occurs when Peerix doesn't have permission to read the private key file.

I think any error in the underlying `nix-serve` process leads to this message.
